### ISSUE TITLE
Cannot get a file from confluence

### ISSUE THREAD

**Issue by Vincent--** [mlf4aiur/SublimeConfluence#3]
Hello,

When I try to get a file using this plugin, I got this error message:
```
ConfluenceApi username: vincent@xxxx.com, password: ***************, base_uri: https://xxxxx.atlassian.net/wiki/rest/api
/Users/vxxxx/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Confluence in /Users/vxxxx/Library/Application Support/Sublime Text 3/Installed Packages/Confluence.sublime-package", line 326, in get_pages
  File "/Users/vxxxx/Library/Application Support/Sublime Text 3/Packages/requests/all/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```

I've tried to use the rest API manually with postman and it works perfectly:

`https://xxxx.atlassian.net/wiki/rest/api/content/search?cql=space=RG%20AND%20type=page%20AND%20title~"deployment"`

```
{
  "results": [
    {
      "id": "12517521",
      "type": "page",
      "status": "current",
      "title": "Deployment",
      "childTypes": {},
      "restrictions": {},
      "_expandable": {
        "container": "",
        "metadata": "",
        "extensions": "",
        "operations": "",
        "children": "",
        "history": "/rest/api/content/12517521/history",
        "ancestors": "",
        "body": "",
        "version": "",
        "descendants": "",
        "space": "/rest/api/space/RG"
      },
      "_links": {
        "self": "https://xxx.atlassian.net/wiki/rest/api/content/12517521",
        "webui": "/display/RG/Deployment",
        "tinyui": "/x/kQC-/"
      }
    }
  ],
  "start": 0,
  "limit": 25,
  "size": 1,
  "_links": {
    "base": "https://xxxx.atlassian.net/wiki",
    "context": "/wiki",
    "self": "https://xxxx.atlassian.net/wiki/rest/api/content/search?cql=space=RG%20AND%20type=page%20AND%20title~%22deployment%22"
  }
}
```

Any idea?

**Comment by mlf4aiur** [comment]
Merged the PR, thanks
